version: '3'

services:
  mysql-container:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rest_db
      - MYSQL_USER=sebastian
      - MYSQL_PASSWORD=123
    volumes:
      - /data/mysql
  spring-rest-app:
    image: spring-rest-app
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-container
    ports:
      - 8080:8080
    volumes:
      - /data/spring-rest-app
